// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.osramos.ss13.proj1.model;

import de.osramos.ss13.proj1.model.TaskdbDataOnDemand;
import de.osramos.ss13.proj1.model.Taskdbgps;
import de.osramos.ss13.proj1.model.TaskdbgpsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TaskdbgpsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TaskdbgpsDataOnDemand: @Component;
    
    private Random TaskdbgpsDataOnDemand.rnd = new SecureRandom();
    
    private List<Taskdbgps> TaskdbgpsDataOnDemand.data;
    
    @Autowired
    TaskdbDataOnDemand TaskdbgpsDataOnDemand.taskdbDataOnDemand;
    
    public Taskdbgps TaskdbgpsDataOnDemand.getNewTransientTaskdbgps(int index) {
        Taskdbgps obj = new Taskdbgps();
        setGpscoordinate(obj, index);
        setPos(obj, index);
        return obj;
    }
    
    public void TaskdbgpsDataOnDemand.setGpscoordinate(Taskdbgps obj, int index) {
        String gpscoordinate = "gpscoordinate_" + index;
        obj.setGpscoordinate(gpscoordinate);
    }
    
    public void TaskdbgpsDataOnDemand.setPos(Taskdbgps obj, int index) {
        Long pos = new Integer(index).longValue();
        obj.setPos(pos);
    }
    
    public Taskdbgps TaskdbgpsDataOnDemand.getSpecificTaskdbgps(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Taskdbgps obj = data.get(index);
        Long id = obj.getId();
        return Taskdbgps.findTaskdbgps(id);
    }
    
    public Taskdbgps TaskdbgpsDataOnDemand.getRandomTaskdbgps() {
        init();
        Taskdbgps obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Taskdbgps.findTaskdbgps(id);
    }
    
    public boolean TaskdbgpsDataOnDemand.modifyTaskdbgps(Taskdbgps obj) {
        return false;
    }
    
    public void TaskdbgpsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Taskdbgps.findTaskdbgpsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Taskdbgps' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Taskdbgps>();
        for (int i = 0; i < 10; i++) {
            Taskdbgps obj = getNewTransientTaskdbgps(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
