// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.osramos.ss13.proj1.model;

import de.osramos.ss13.proj1.model.Taskdbgps;
import de.osramos.ss13.proj1.model.TaskdbgpsDataOnDemand;
import de.osramos.ss13.proj1.model.TaskdbgpsIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TaskdbgpsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TaskdbgpsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TaskdbgpsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TaskdbgpsIntegrationTest: @Transactional;
    
    @Autowired
    TaskdbgpsDataOnDemand TaskdbgpsIntegrationTest.dod;
    
    @Test
    public void TaskdbgpsIntegrationTest.testCountTaskdbgpses() {
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to initialize correctly", dod.getRandomTaskdbgps());
        long count = Taskdbgps.countTaskdbgpses();
        Assert.assertTrue("Counter for 'Taskdbgps' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TaskdbgpsIntegrationTest.testFindTaskdbgps() {
        Taskdbgps obj = dod.getRandomTaskdbgps();
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to provide an identifier", id);
        obj = Taskdbgps.findTaskdbgps(id);
        Assert.assertNotNull("Find method for 'Taskdbgps' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Taskdbgps' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TaskdbgpsIntegrationTest.testFindAllTaskdbgpses() {
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to initialize correctly", dod.getRandomTaskdbgps());
        long count = Taskdbgps.countTaskdbgpses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Taskdbgps', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Taskdbgps> result = Taskdbgps.findAllTaskdbgpses();
        Assert.assertNotNull("Find all method for 'Taskdbgps' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Taskdbgps' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TaskdbgpsIntegrationTest.testFindTaskdbgpsEntries() {
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to initialize correctly", dod.getRandomTaskdbgps());
        long count = Taskdbgps.countTaskdbgpses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Taskdbgps> result = Taskdbgps.findTaskdbgpsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Taskdbgps' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Taskdbgps' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TaskdbgpsIntegrationTest.testFlush() {
        Taskdbgps obj = dod.getRandomTaskdbgps();
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to provide an identifier", id);
        obj = Taskdbgps.findTaskdbgps(id);
        Assert.assertNotNull("Find method for 'Taskdbgps' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTaskdbgps(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Taskdbgps' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TaskdbgpsIntegrationTest.testMergeUpdate() {
        Taskdbgps obj = dod.getRandomTaskdbgps();
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to provide an identifier", id);
        obj = Taskdbgps.findTaskdbgps(id);
        boolean modified =  dod.modifyTaskdbgps(obj);
        Integer currentVersion = obj.getVersion();
        Taskdbgps merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Taskdbgps' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TaskdbgpsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to initialize correctly", dod.getRandomTaskdbgps());
        Taskdbgps obj = dod.getNewTransientTaskdbgps(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Taskdbgps' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Taskdbgps' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TaskdbgpsIntegrationTest.testRemove() {
        Taskdbgps obj = dod.getRandomTaskdbgps();
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Taskdbgps' failed to provide an identifier", id);
        obj = Taskdbgps.findTaskdbgps(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Taskdbgps' with identifier '" + id + "'", Taskdbgps.findTaskdbgps(id));
    }
    
}
