// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.osramos.ss13.proj1.model;

/*
 * #%L
 * proj1
 * %%
 * Copyright (C) 2013 Amos-Project
 * %%
 * Copyright (c) 2013 by Alexander Schmidt, Sascha Ströbel, Nina Aures, Riehle, http://dirkriehle.com
 * -
 * This file is part of the Amos Project - Productive Games application.
 * -
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * -
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * -
 * You should have received a copy of the GNU Affero General Public
 * License along with this program. If not, see
 * <http://www.gnu.org/licenses/>.
 * #L%
 */

import de.osramos.ss13.proj1.model.UserRole;
import de.osramos.ss13.proj1.model.Userdb;
import de.osramos.ss13.proj1.model.UserdbDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserdbDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserdbDataOnDemand: @Component;
    
    private Random UserdbDataOnDemand.rnd = new SecureRandom();
    
    private List<Userdb> UserdbDataOnDemand.data;
    
    public Userdb UserdbDataOnDemand.getNewTransientUserdb(int index) {
        Userdb obj = new Userdb();
        setFirstname(obj, index);
        setLastname(obj, index);
        setPassword(obj, index);
        setUsername(obj, index);
        setUserrole(obj, index);
        return obj;
    }
    
    public void UserdbDataOnDemand.setFirstname(Userdb obj, int index) {
        String firstname = "firstname_" + index;
        obj.setFirstname(firstname);
    }
    
    public void UserdbDataOnDemand.setLastname(Userdb obj, int index) {
        String lastname = "lastname_" + index;
        obj.setLastname(lastname);
    }
    
    public void UserdbDataOnDemand.setPassword(Userdb obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void UserdbDataOnDemand.setUsername(Userdb obj, int index) {
        String username = "username_" + index;
        obj.setUsername(username);
    }
    
    public void UserdbDataOnDemand.setUserrole(Userdb obj, int index) {
        UserRole userrole = null;
        obj.setUserrole(userrole);
    }
    
    public Userdb UserdbDataOnDemand.getSpecificUserdb(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Userdb obj = data.get(index);
        Long id = obj.getId();
        return Userdb.findUserdb(id);
    }
    
    public Userdb UserdbDataOnDemand.getRandomUserdb() {
        init();
        Userdb obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Userdb.findUserdb(id);
    }
    
    public boolean UserdbDataOnDemand.modifyUserdb(Userdb obj) {
        return false;
    }
    
    public void UserdbDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Userdb.findUserdbEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Userdb' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Userdb>();
        for (int i = 0; i < 10; i++) {
            Userdb obj = getNewTransientUserdb(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
