// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.osramos.ss13.proj1.model;

import de.osramos.ss13.proj1.model.Taskdbgps;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Taskdbgps_Roo_Configurable {
    
    declare @type: Taskdbgps: @Configurable;
    
}
